export const menuItems = {
    burgers: [
        {
            id:1,
            name: '',
            description: '',
            price: '',
            type:''
        },
        {
            id:2,
            name:'',
            description:'',
            price:'',
            type:''
        },
        {
            id:3,
            name:'',
            description:'',
            price:'',
            type:''
        },
        {
            id:4,
            name:'',
            description:'',
            price:'',
            type:''
        },
        {
            id:5,
            name:'',
            description:'',
            price:'',
            type:''
        }
    ],
    steaks:[
        {
            id:1,
            name:'',
            description:'',
            price:'',
            type:''
        },
        {
            id:2,
            name:'',
            description:'',
            price:'',
            type:''
        },
        {
            id:3,
            name:'',
            description:'',
            price:'',
            type:''
        },
        {
            id:4,
            name:'',
            description:'',
            price:'',
            type:''
        },
        {
            id:5,
            name:'',
            description:'',
            price:'',
            type:''
        }
    ],
    desserts:[
        {
            id:1,
            name:'',
            description:'',
            price:'',
            type:''
        },
        {
            id:2,
            name:'',
            description:'',
            price:'',
            type:''
        },
        {
            id:3,
            name:'',
            description:'',
            price:'',
            type:''
        }
    ]
}